### ISSUE TITLE
Crashes when supplying non english characters for password

### ISSUE THREAD

**Issue by tarasis** [tarasis/QuietUnrar#1]
Stack trace from GDB:

Program received signal:  “EXC_BAD_ACCESS”.
sharedlibrary apply-load-rules all
(gdb) bt
#0  0x00007fff84ba8e00 in strncpy ()
#1  0x0000000100007d4e in strncpyz ()
#2  0x0000000100031e34 in RARSetPassword ()
#3  0x000000010000177e in callbackFunction () at QuietUnrarAppDelegate.m:54
#4  0x000000010001f237 in CmdExtract::ExtractCurrentFile ()
#5  0x0000000100032130 in ProcessFile ()
#6  0x000000010003228a in RARProcessFile ()
#7  0x0000000100001c26 in -[QuietUnrarAppDelegate extractRarWith:]() at QuietUnrarAppDelegate.m:132
#8  0x00000001000018e9 in -[QuietUnrarAppDelegate application:openFiles:]() at QuietUnrarAppDelegate.m:91
#9  0x00007fff80c8c49b in -[NSApplication _doOpenFile:ok:tryTemp:]()
#10 0x00007fff80a74d02 in -[NSApplication finishLaunching]()
#11 0x00007fff80a7460c in -[NSApplication run]()
#12 0x00007fff80a6d468 in NSApplicationMain ()
#13 0x00000001000016f9 in main () at main.m:13

**Comment by tarasis** [comment]
No longer crashes when supplying non English characters.
